# Generated by Django 6.0.3 on 2026-03-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mutaxasislar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_n", models.CharField(max_length=120, verbose_name="Ismi")),
                ("last_n", models.CharField(max_length=100, verbose_name="Familiya")),
                ("age", models.IntegerField(verbose_name="Yoshi")),
                ("country", models.CharField(max_length=100, verbose_name="Davlati")),
                ("experience", models.IntegerField(verbose_name="Tajriba")),
                (
                    "prof",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Sohasi"
                    ),
                ),
                ("salary", models.IntegerField(verbose_name="Maoshi")),
            ],
        ),
    ]
