# Generated by Django 6.0.3 on 2026-03-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dorilar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="Nomi")),
                ("brand", models.CharField(max_length=100, verbose_name="Brand")),
                ("country", models.CharField(max_length=100, verbose_name="Davlati")),
                ("year", models.IntegerField(verbose_name="Chiqarilgan yili")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Narxi"
                    ),
                ),
                ("stock", models.IntegerField(verbose_name="Soni")),
                (
                    "age",
                    models.CharField(
                        choices=[("0+", "0+"), ("12+", "12+"), ("18+", "18+")],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
