# Generated by Django 5.0.1 on 2026-03-21 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Books",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="Nomi")),
                ("author", models.CharField(max_length=100, verbose_name="Avtor")),
                ("country", models.CharField(max_length=100, verbose_name="Davlati")),
                ("year", models.IntegerField(verbose_name="Chop etilgan yili")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Narxi"
                    ),
                ),
                ("stock", models.IntegerField(verbose_name="Soni")),
                ("rating", models.IntegerField(max_length=100, verbose_name="Rating")),
            ],
        ),
    ]
