# Generated by Django 5.0.1 on 2026-03-25 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_author_book_bookcategory_category_delete_books_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                to="books.category",
            ),
            preserve_default=False,
        ),
    ]
