# Generated by Django 5.0.1 on 2026-03-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Motos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("make", models.CharField(max_length=120, verbose_name="Make")),
                ("brand", models.CharField(max_length=100, verbose_name="Brand")),
                ("country", models.CharField(max_length=100, verbose_name="Davlati")),
                ("year", models.IntegerField(verbose_name="Chiqarilgan yili")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Narxi"
                    ),
                ),
                ("stock", models.IntegerField(verbose_name="Soni")),
                ("color", models.CharField(max_length=100, verbose_name="Rangi")),
                ("max_speed", models.IntegerField(verbose_name="Maximal tezligi")),
            ],
        ),
    ]
