# Generated by Django 5.0.1 on 2026-03-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Phones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=100, verbose_name="Brendi")),
                (
                    "model_name",
                    models.CharField(max_length=120, verbose_name="Model nomi"),
                ),
                (
                    "memory",
                    models.CharField(max_length=100, verbose_name="Xotirasi (RAM/ROM)"),
                ),
                ("color", models.CharField(max_length=100, verbose_name="Rangi")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Narxi"
                    ),
                ),
                ("stock", models.IntegerField(verbose_name="Soni (Omborda)")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Qisqacha ma'lumot"),
                ),
            ],
            options={
                "verbose_name": "Telefon",
                "verbose_name_plural": "Telefonlar",
            },
        ),
    ]
