# Generated by Django 5.0.1 on 2026-03-28 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("phones", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="phones",
            table="phones",
        ),
    ]
